# Change these first
owner: orfeotoolbox # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: Forge
    url: https://gitlab.orfeo-toolbox.org
  - name: Forum
    url: https://forum.orfeo-toolbox.org
  - name: Website
    url: https://www.orfeo-toolbox.org
  - name: Cdash
    url: https://cdash.orfeo-toolbox.org
  - name: Code Quality Analysis
    url: https://sonar.orfeo-toolbox.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.orfeo-toolbox.org
  # baseUrl: /your-repo-name
  logoUrl: https://www.orfeo-toolbox.org/wp-content/uploads/2016/03/logo-orfeo-toolbox.png
  name: Orfeo Toolbox Services Status
  introTitle: "This is the uptime monitor and status page for the **Orfeo Toolbox** project."
  introMessage: If a service doesn't work properly, you may find the reason here. If not, please open an issue.
  navbar:
    - title: Status
      href: /
    - title: Forum
      href: https://forum.orfeo-toolbox.org/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
assignees:
  - Julien-Osman
  - tromain

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
